name: Deploy to GH Pages

on:
  push:
    branches: [Main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: install dependencies
        run: npm ci

      - name: build app
        run: npm run build
        env:
          REACT_APP_BASENAME: ${{ vars.BASENAME }}
          REACT_APP_BOOKS_API_KEY: ${{ secrets.BOOKS_API_KEY }}
          PUBLIC_URL: /test-task-Future

      - name: upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build

      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v1
